/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.ControlProductos;
import objetosNegocio.Empleado;
import objetosNegocio.Producto;
import objetosNegocio.ProductoVenta;

/**
 *
 * @author GPE
 */
public class FrmPuntoDeVenta extends javax.swing.JFrame {

    Empleado empleado;

    /**
     * Creates new form FrmPuntoDeVenta
     */
    public FrmPuntoDeVenta(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        this.cargarBanner();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBanner = new javax.swing.JLabel();
        lblEncabezado = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tblProductosVenta = new javax.swing.JTable();
        lblPanda = new javax.swing.JLabel();
        lblJMJR = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        txtBascula = new javax.swing.JTextField();
        txtCodBarras = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblMenuSupervisor = new javax.swing.JLabel();
        lblSoporte = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de Venta \"Abarrotes el Panda\"");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBanner.setBackground(new java.awt.Color(255, 255, 255));
        lblBanner.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(0, 51, 255));
        lblBanner.setText("Hola");
        getContentPane().add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 30));

        lblEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        lblEncabezado.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner.png"))); // NOI18N
        getContentPane().add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        tblProductosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo de Barras", "Cantidad", "Descripción", "Precio", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTabla.setViewportView(tblProductosVenta);

        getContentPane().add(scrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 510));

        lblPanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N
        getContentPane().add(lblPanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, -1, -1));

        lblJMJR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/panda.jpg"))); // NOI18N
        getContentPane().add(lblJMJR, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Gigi", 3, 30)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo1.setText("Abarrotes el Panda");
        getContentPane().add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 300, 30));

        txtBascula.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtBascula.setForeground(new java.awt.Color(0, 51, 255));
        txtBascula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBascula.setText("1");
        txtBascula.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtBascula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBasculaActionPerformed(evt);
            }
        });
        getContentPane().add(txtBascula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 140, 40));

        txtCodBarras.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCodBarras.setForeground(new java.awt.Color(0, 51, 255));
        txtCodBarras.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCodBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodBarrasKeyReleased(evt);
            }
        });
        getContentPane().add(txtCodBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 260, 40));

        lblTotal.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        txtTotal.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 51, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setText("0.00");
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 220, 70));

        txtCantidad.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(0, 51, 255));
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad.setText("0");
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 160, 40));

        jButton1.setText("Cobrar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 80, 40));

        lblMenuSupervisor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMenuSupervisor.setForeground(new java.awt.Color(204, 0, 0));
        lblMenuSupervisor.setText("F3- Menu Administrador.");
        getContentPane().add(lblMenuSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, -1, -1));

        lblSoporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSoporte.setForeground(new java.awt.Color(204, 0, 0));
        lblSoporte.setText("F2- Ayuda o Soporte");
        getContentPane().add(lblSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        lblFondo.setFont(new java.awt.Font("Sylfaen", 3, 36)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPV.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBasculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBasculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBasculaActionPerformed

    private void txtCodBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodBarrasKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                this.leerCampoCodigoBarras();
            } catch (SQLException ex) {
                Logger.getLogger(FrmPuntoDeVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            FrmAyuda frmAyuda = new FrmAyuda();
            frmAyuda.setVisible(true);
        }
        if (evt.getKeyCode() == KeyEvent.VK_F3) {
            FrmMenuSupervisor frmMenuSupervisor = new FrmMenuSupervisor();
            frmMenuSupervisor.setVisible(true);
        }
    }//GEN-LAST:event_txtCodBarrasKeyReleased

    private void leerCampoCodigoBarras() throws SQLException {
        String textoCodigoDeBarras = txtCodBarras.getText();
        if (textoCodigoDeBarras.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Este campo no puede estar vacio.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else if (textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'E' || textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'e') {
            JOptionPane.showMessageDialog(null, "Aqui va el codigo de cobro en efectivo.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else if (textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'T' || textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 't') {
            JOptionPane.showMessageDialog(null, "Aqui va el codigo de cobro en tarjeta.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else if (textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'c' || textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'C') {
            JOptionPane.showMessageDialog(null, "Aqui va el codigo de cobro a credito.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else if (textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'Q' || textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'q') {
            JOptionPane.showMessageDialog(null, "Aqui va el codigo de cobro de cancelar articulo.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else if (textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'B' || textoCodigoDeBarras.charAt(textoCodigoDeBarras.length() - 1) == 'b') {
            JOptionPane.showMessageDialog(null, "Aqui va el codigo de cobro de buscar.", "Error En Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            this.escanearProducto();
        }

    }

    private void actualizarStock(String codBarras) throws SQLException {
        Producto producto = this.controlProductos.obtenerProductoCodBarras(codBarras);
        producto.setStock(producto.getStock() - 1);
        this.controlProductos.actualizarStock(producto.getId(), producto);
    }

    private void agregarProducto(String codBarras) throws SQLException {
        Producto producto = this.controlProductos.obtenerProductoCodBarras(codBarras);
        producto.setStock(producto.getStock() - 1);
        this.controlProductos.actualizarStock(producto.getId(), producto);
    }

    private void cargarBanner() {
        String banner = "Caja 1                            Empleado:" + this.empleado.getId() + "                          Tipo:" + this.empleado.getTipo() + "                             Estado: En Linea                                 " + new Date() + "";
        lblBanner.setText(banner);
    }

    private void escanearProducto() throws SQLException {
        DefaultTableModel modeloEscaneados = (DefaultTableModel) tblProductosVenta.getModel();
        ProductoVenta productos = new ProductoVenta();
        String codBarras = txtCodBarras.getText();
        this.actualizarStock(codBarras);
        Producto producto;
        try {
            producto = controlProductos.obtenerProductoCodBarras(codBarras);
            for (int i = 0; i < modeloEscaneados.getRowCount(); i++) {
                if (codBarras.equals(modeloEscaneados.getValueAt(i, 0) + "")) {
                    Float cantidad = (Float) modeloEscaneados.getValueAt(i, 1) + Float.parseFloat(txtBascula.getText());
                    producto.setStock(producto.getStock() - 1);
                    Float montoTotal = producto.getPrecioActual() * cantidad;
                    modeloEscaneados.setValueAt(cantidad, i, 1);
                    modeloEscaneados.setValueAt(montoTotal, i, 4);
                    this.actualizarCampos();
                    return;
                }

            }
            productos.setProducto(producto);
            productos.setPrecio(producto.getPrecioActual());
            productos.setCantidad(Float.parseFloat(txtBascula.getText()));
            productos.setMontoTotal(productos.getPrecio() * productos.getCantidad());
        } catch (SQLException ex) {
            Logger.getLogger(FrmPuntoDeVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        modeloEscaneados.addRow(productos.toArray());
        this.actualizarCampos();
    }

    private void actualizarCampos() {
        DefaultTableModel modeloEscaneados = (DefaultTableModel) tblProductosVenta.getModel();
        Float subtotal = 0F;
        for (int i = 0; i < modeloEscaneados.getRowCount(); i++) {
            subtotal += (Float) modeloEscaneados.getValueAt(i, 4);
        }
        txtTotal.setText(subtotal + "");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJMJR;
    private javax.swing.JLabel lblMenuSupervisor;
    private javax.swing.JLabel lblPanda;
    private javax.swing.JLabel lblSoporte;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tblProductosVenta;
    private javax.swing.JTextField txtBascula;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    ControlProductos controlProductos = new ControlProductos();
}
